name: Marketplace licenses → Slack

on:
  schedule:
    - cron: "*/5 * * * *"   # TEMP: every 5 minutes (UTC) to verify scheduling
    - cron: "30 6 * * *"   # 08:30 Kyiv when UTC+2 (winter), 09:30 when UTC+3 (summer)
  workflow_dispatch:          # allow manual runs

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- debug: show current UTC time in logs
      - name: Show UTC time
        run: date -u

      # --- debug: Slack smoke test (should appear immediately in your channel)
      - name: Slack smoke test
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -fsS -X POST -H 'Content-type: application/json' \
            --data '{"text":"(smoke) GitHub Actions can post to this webhook."}' \
            "$SLACK_WEBHOOK"

      - run: pip install -r requirements.txt

      - name: Notify Slack about new items
        env:
          MP_USER: ${{ secrets.MP_USER }}
          MP_API_TOKEN: ${{ secrets.MP_API_TOKEN }}
          VENDOR_ID: ${{ secrets.VENDOR_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          # Optional backfill for manual runs:
          # DAY: "2025-10-10"
        run: python src/notify_licenses.py
